"""empty message

Revision ID: 549c9fcdb262
Revises: fdac19ab35df
Create Date: 2021-09-10 14:17:34.958223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '549c9fcdb262'
down_revision = 'fdac19ab35df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_character', sa.Column('type', sa.String(length=80), nullable=True))
    op.add_column('favorite_character', sa.Column('favorite_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorite_character_ibfk_1', 'favorite_character', type_='foreignkey')
    op.drop_constraint('favorite_character_ibfk_3', 'favorite_character', type_='foreignkey')
    op.drop_column('favorite_character', 'planet_id')
    op.drop_column('favorite_character', 'character_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_character', sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorite_character', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorite_character_ibfk_3', 'favorite_character', 'planet', ['planet_id'], ['id'])
    op.create_foreign_key('favorite_character_ibfk_1', 'favorite_character', 'character', ['character_id'], ['id'])
    op.drop_column('favorite_character', 'favorite_id')
    op.drop_column('favorite_character', 'type')
    # ### end Alembic commands ###
