"""empty message

Revision ID: fc4b0625b733
Revises: 4280545ffe7d
Create Date: 2021-09-10 20:18:34.653822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4b0625b733'
down_revision = '4280545ffe7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('type', sa.String(length=80), nullable=False))
    op.add_column('planet', sa.Column('type', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'type')
    op.drop_column('character', 'type')
    # ### end Alembic commands ###
