"""empty message

Revision ID: fdac19ab35df
Revises: 30e77ecac70d
Create Date: 2021-09-10 10:08:05.119167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdac19ab35df'
down_revision = '30e77ecac70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_planet')
    op.add_column('favorite_character', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite_character', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.drop_column('favorite_character', 'planet_id')
    op.create_table('favorite_planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
